#!/usr/bin/env bash
# Materialize per-agent timer drop-ins from manifests (architecture.md §6).
# Run on the VPS after adding or rescheduling an agent. Requires sudo + jq.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
changed=0

for manifest in "$root"/agents/*/agent.json; do
  [[ "$manifest" == */_examples/* ]] && continue
  id="$(jq -r .id "$manifest")"
  cal="$(jq -r '.schedule.onCalendar // empty' "$manifest")"
  if [[ -z "$cal" ]]; then
    echo "sync-units: $id has no schedule, skipping"
    continue
  fi
  dropin_dir="/etc/systemd/system/fleet-agent@$id.timer.d"
  sudo mkdir -p "$dropin_dir"
  printf '# Generated by scripts/sync-units.sh from agents/%s/agent.json — do not edit.\n[Timer]\nOnCalendar=%s\n' \
    "$id" "$cal" | sudo tee "$dropin_dir/schedule.conf" >/dev/null
  echo "sync-units: $id → OnCalendar=$cal"
  changed=1
done

if [[ "$changed" == 1 ]]; then
  sudo systemctl daemon-reload
  for manifest in "$root"/agents/*/agent.json; do
    [[ "$manifest" == */_examples/* ]] && continue
    id="$(jq -r .id "$manifest")"
    [[ -n "$(jq -r '.schedule.onCalendar // empty' "$manifest")" ]] &&
      sudo systemctl enable --now "fleet-agent@$id.timer"
  done
fi
